/**
 * Curated city/region → country gazetteer for Corveno's seven launch markets.
 * Data only; the matching rules live in ./location-gazetteer.ts.
 *
 * Conventions
 * - Each list item is one place. Alternate surface forms are separated by "|"
 *   ("Bengaluru|Bangalore"). Forms are matched as whole tokens or whole token
 *   phrases after NFKC + casefold + Latin diacritic stripping, never as
 *   substrings ("Bathurst" can never match "Bath").
 * - A form listed under two countries (Cambridge: GB, US, CA) is AUTOMATICALLY
 *   ambiguous: it is only positive when a disambiguating region, region code or
 *   explicit country of one candidate is present in the same location.
 * - `gazetteerModifiers` add ambiguity the seven-market lists cannot express
 *   (a name shared with a well-known place outside the markets, or a name the
 *   product must never assume even inside one country), the London default
 *   rule, and whole-segment-only guards for names that are ordinary words.
 * - Region codes match only when written in upper case in the label. Codes in
 *   `guardedRegionCodes` (word-like: DE, ME, OR, IN, ON, …) are accepted only
 *   directly after a known city and comma ("Austin, TX"), beside an explicit
 *   country ("US-TX", "TX, USA") or after "Remote -" when unambiguous is NOT
 *   enough — a guarded code alone is ignored. Every Indian state code is
 *   guarded (`anchorRequiredCodeCountries`) because most collide with ISO
 *   country codes or ordinary abbreviations (HR, BR, UP, TN, GA, CH, PY).
 * - "CA" and "IN" read both as a US state code and as a country
 *   (`countryCollisionCodes`); they never resolve on their own.
 */
import type { SupportedMarket } from "./country-evidence";

export type GazetteerKind = "city" | "region" | "region_code" | "metro";

export interface GazetteerCountryData {
  /** First-level administrative divisions (states, provinces, nations, prefectures). */
  regions: string[];
  /** Abbreviations actually used in postings; matched in upper case only. */
  regionCodes: string[];
  /** Largest cities, suburbs and localities used as job locations. */
  cities: string[];
  /** Metros, business districts and multi-city areas used as job locations. */
  metros: string[];
}

export interface GazetteerModifier {
  /** Never positive without a disambiguating token in the same location. */
  ambiguous?: true;
  /** Extra candidate countries sharing the name: other launch markets or
   * well-known places outside the markets (ISO codes such as PK, FR, GE). */
  alsoCountries?: string[];
  /** A lone mention resolves to this market at medium confidence unless a
   * competing candidate country is evidenced anywhere in the label. Used for
   * London only: GB unless an Ontario/ON/Canada-side token is present. */
  defaultCountry?: SupportedMarket;
  /** The name is also an ordinary word: accept only as a complete segment. */
  wholeSegmentOnly?: true;
  note?: string;
}

export const gazetteerSource: Record<SupportedMarket, GazetteerCountryData> = {
  US: {
    regions: [
      "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware",
      "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky",
      "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi",
      "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
      "New York|New York State", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
      "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah",
      "Vermont", "Virginia", "Washington|Washington State", "West Virginia", "Wisconsin", "Wyoming",
      "District of Columbia|Washington DC|Washington D C", "Puerto Rico",
    ],
    regionCodes: [
      "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS",
      "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
      "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
      "WI", "WY", "DC", "PR",
    ],
    cities: [
      "New York City|NYC", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio",
      "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte",
      "San Francisco", "Indianapolis", "Seattle", "Denver", "Boston", "El Paso", "Nashville", "Detroit",
      "Oklahoma City", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee",
      "Albuquerque", "Tucson", "Fresno", "Mesa", "Sacramento", "Atlanta", "Kansas City", "Colorado Springs",
      "Omaha", "Raleigh", "Miami", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tulsa",
      "Tampa", "Arlington", "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora", "Anaheim",
      "Honolulu", "Santa Ana", "Riverside", "Corpus Christi", "Lexington", "Stockton", "Henderson",
      "Saint Paul|St Paul", "Saint Louis|St Louis", "Cincinnati", "Pittsburgh", "Greensboro", "Anchorage",
      "Plano", "Lincoln", "Orlando", "Irvine", "Newark", "Durham", "Chula Vista", "Toledo", "Fort Wayne",
      "Saint Petersburg|St Petersburg", "Laredo", "Jersey City", "Chandler", "Madison", "Lubbock",
      "Scottsdale", "Reno", "Buffalo", "Glendale", "Winston-Salem", "Chesapeake", "Norfolk", "Fremont",
      "Hialeah", "Richmond", "Boise", "Spokane", "Baton Rouge", "Tacoma", "San Bernardino", "Modesto",
      "Des Moines", "Fayetteville", "Birmingham", "Rochester", "Grand Rapids", "Huntsville",
      "Salt Lake City", "Frisco", "Yonkers", "Amarillo", "Huntington Beach", "McKinney", "Akron",
      "Little Rock", "Tempe", "Overland Park", "Tallahassee", "Knoxville", "Worcester", "Ontario",
      "Vancouver", "Sioux Falls", "Chattanooga", "Fort Lauderdale", "Santa Rosa", "Peoria", "Salem",
      "Cary", "Fort Collins", "Springfield", "Alexandria", "Hayward", "Lakewood", "Lancaster", "Pasadena",
      "Sunnyvale", "Bellevue", "Bridgeport", "Torrance", "Syracuse", "Charleston", "Waco", "Columbia",
      "Round Rock", "Cedar Rapids", "Sterling", "Santa Clara", "Mountain View", "Palo Alto", "Menlo Park",
      "Redwood City", "Cupertino", "San Mateo", "South San Francisco", "Berkeley", "Redmond", "Kirkland",
      "Boulder", "Ann Arbor", "Cambridge", "Princeton", "Stamford", "Hartford", "New Haven", "Albany",
      "Bethesda", "Reston", "McLean", "Tysons|Tysons Corner", "Herndon", "Chapel Hill", "Provo", "Lehi",
      "Boca Raton", "Sarasota", "Gainesville", "Bozeman", "Fargo", "Lansing", "Dayton", "Scranton",
      "Allentown", "Harrisburg", "Wilmington", "Dover", "Annapolis", "Roanoke", "Greenville", "Asheville",
      "Topeka", "Manhattan", "Brooklyn", "Bronx", "Staten Island", "Queens", "Hollywood", "Burbank",
      "Santa Monica", "Culver City", "Irving", "Manchester", "Kingston", "Windsor", "Waterloo", "Halifax",
      "Hamilton", "Melbourne", "Paris", "Georgetown", "Bath", "Reading", "Brighton", "York", "Plymouth",
      "Portsmouth", "Newport", "Warwick", "Bedford", "Chatham", "Burlington", "Milton", "Woodstock",
      "Belleville", "Niagara Falls", "White Rock", "Langley", "Bangor", "Livingston", "The Woodlands|Woodlands",
      "Perth Amboy", "Oxford", "Bristol", "Southampton", "Westminster", "Camden", "Greenwich", "Carlisle",
      "Chester", "Wakefield", "Northampton", "Chelmsford", "Aberdeen", "Lincoln Park", "Naperville",
      "Schaumburg", "Evanston", "Rockville", "Silver Spring", "Jersey Shore", "Hoboken", "White Plains",
      "Stamford", "New Brunswick", "Piscataway", "Edison", "Morristown", "Parsippany", "Cherry Hill",
      "King of Prussia", "Conshohocken", "Malvern", "Wayne", "Ithaca", "Rochester Hills", "Troy", "Dearborn",
      "Bloomington", "Champaign", "Urbana", "Iowa City", "Ames", "Lawrence", "Norman", "Stillwater",
      "College Station", "Plano", "Richardson", "Sugar Land", "The Woodlands", "Katy", "Pearland",
      "Santa Barbara", "San Luis Obispo", "Santa Cruz", "Monterey", "Carlsbad", "La Jolla", "Oceanside",
      "Escondido", "Temecula", "Ventura", "Oxnard", "Thousand Oaks", "Simi Valley", "Walnut Creek",
      "Pleasanton", "Dublin", "Livermore", "San Ramon", "Concord", "Emeryville", "Alameda", "Foster City",
      "Burlingame", "Millbrae", "Los Gatos", "Campbell", "Milpitas", "Newark", "Union City", "Vallejo",
      "Napa", "Santa Rosa", "Petaluma", "Davis", "Roseville", "Folsom", "Elk Grove", "Chico", "Redding",
      "Eugene", "Salem", "Bend", "Beaverton", "Hillsboro", "Vancouver", "Olympia", "Everett", "Bothell",
      "Renton", "Kent", "Federal Way", "Bellingham", "Yakima", "Coeur d'Alene|Coeur dAlene", "Missoula",
      "Billings", "Cheyenne", "Casper", "Sioux City", "Lincoln", "Grand Island", "Rapid City", "Bismarck",
      "Duluth", "Rochester", "Bloomington", "Eden Prairie", "Green Bay", "Appleton", "Kenosha", "Racine",
      "Ann Arbor", "Flint", "Kalamazoo", "Toledo", "Columbus", "Akron", "Canton", "Youngstown",
      "Louisville", "Lexington", "Bowling Green", "Memphis", "Chattanooga", "Murfreesboro", "Franklin",
      "Jackson", "Gulfport", "Mobile", "Montgomery", "Tuscaloosa", "Savannah", "Augusta", "Macon",
      "Athens", "Alpharetta", "Marietta", "Columbia", "Charleston", "Myrtle Beach", "Wilmington",
      "Greensboro", "Winston-Salem", "Durham", "Cary", "Norfolk", "Newport News", "Hampton", "Richmond",
      "Fairfax", "Arlington", "Alexandria", "Chantilly", "Leesburg", "Ashburn", "Frederick", "Columbia",
      "Baltimore", "Towson", "Annapolis", "Dover", "Newark", "Trenton", "Camden", "Atlantic City",
      "New Brunswick", "Providence", "Warwick", "Hartford", "New Haven", "Stamford", "Bridgeport",
      "Springfield", "Worcester", "Lowell", "Waltham", "Burlington", "Lexington", "Quincy", "Newton",
      "Somerville", "Medford", "Nashua", "Manchester", "Concord", "Portland", "Burlington", "Montpelier",
      "Honolulu", "Juneau", "Fairbanks", "San Juan",
    ],
    metros: [
      "Bay Area", "San Francisco Bay Area", "SF Bay Area", "Silicon Valley", "Greater Boston",
      "Greater Seattle", "Greater Los Angeles", "Greater Philadelphia", "Greater Chicago", "Chicagoland",
      "Twin Cities", "Dallas-Fort Worth|DFW", "Research Triangle", "Inland Empire", "Orange County",
      "South Florida", "Central Florida", "Northern Virginia|NoVA", "New England", "Southern California|SoCal",
      "Northern California|NorCal", "East Bay", "South Bay", "Westchester", "Long Island", "Hudson Valley",
      "Tri-State Area", "DC Metro", "Washington Metro", "Greater Washington", "Greater Houston",
      "Greater Denver", "Greater Atlanta", "Greater Phoenix", "Greater Austin", "Metro Detroit",
      "Greater New York", "Greater Miami", "Greater San Diego", "Greater Portland", "Puget Sound",
      "Rocky Mountain Region", "Midwest", "Pacific Northwest", "New York Metro", "Tri-Valley",
    ],
  },
  CA: {
    regions: [
      "Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador|Newfoundland",
      "Nova Scotia", "Ontario", "Prince Edward Island|PEI", "Quebec|Québec", "Saskatchewan",
      "Northwest Territories", "Nunavut", "Yukon",
    ],
    regionCodes: ["AB", "BC", "MB", "NB", "NL", "NS", "ON", "PE", "QC", "SK", "NT", "NU", "YT"],
    cities: [
      "Toronto", "Montreal|Montréal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg",
      "Mississauga", "Brampton", "Hamilton", "Surrey", "Halifax", "Laval", "London", "Markham", "Vaughan",
      "Gatineau", "Saskatoon", "Kitchener", "Waterloo", "Longueuil", "Burnaby", "Regina", "Richmond",
      "Richmond Hill", "Oakville", "Burlington", "Sherbrooke", "Oshawa", "Greater Sudbury|Sudbury",
      "Saguenay", "Lévis|Levis", "Barrie", "Abbotsford", "Coquitlam", "Trois-Rivières|Trois Rivieres",
      "St Catharines|Saint Catharines", "Guelph", "Cambridge", "Whitby", "Kelowna", "Kingston", "Ajax",
      "Langley", "Thunder Bay", "Chatham", "Delta", "Red Deer", "Kamloops", "Brantford", "Cape Breton",
      "Lethbridge", "Saint-Jean-sur-Richelieu|Saint Jean sur Richelieu", "Clarington", "Pickering",
      "Nanaimo", "Chilliwack", "Maple Ridge", "New Westminster", "North Vancouver", "West Vancouver",
      "Port Coquitlam", "Moncton", "Fredericton", "Saint John", "St Johns|Saint Johns", "Charlottetown",
      "Dartmouth", "Sydney", "Quebec City|Ville de Québec|Ville de Quebec", "Drummondville", "Granby",
      "Brossard", "Terrebonne", "Repentigny", "Blainville", "Milton", "Newmarket", "Aurora", "Peterborough",
      "Belleville", "Sarnia", "Niagara Falls", "Welland", "North Bay", "Timmins", "Cornwall", "Woodstock",
      "Stratford", "Orillia", "Bradford", "Medicine Hat", "Grande Prairie", "Fort McMurray", "Airdrie",
      "Prince George", "Prince Albert", "Moose Jaw", "Brandon", "Whitehorse", "Yellowknife", "Iqaluit",
      "Victoria", "Whistler", "Squamish", "Windsor", "Etobicoke", "Scarborough", "North York", "Truro",
      "Hull", "Kirkland", "White Rock", "Georgetown", "Paris", "Perth", "Bathurst", "Bolton", "Collingwood",
      "Saanich", "Sidney", "Mont-Tremblant|Mont Tremblant", "Boucherville", "Dorval", "Pointe-Claire|Pointe Claire",
      "Saint-Laurent|Saint Laurent|Ville Saint-Laurent", "Anjou", "Verdun", "Westmount", "Outremont",
      "Lachine", "LaSalle|Lasalle", "Rimouski", "Chicoutimi", "Rouyn-Noranda|Rouyn Noranda", "Val-d'Or|Val dOr",
      "Sept-Îles|Sept Iles", "Baie-Comeau|Baie Comeau", "Shawinigan", "Victoriaville", "Saint-Hyacinthe|Saint Hyacinthe",
      "Joliette", "Sorel-Tracy|Sorel Tracy", "Magog", "Thetford Mines", "Rivière-du-Loup|Riviere du Loup",
      "Stoney Creek", "Ancaster", "Dundas", "Grimsby", "Oakville", "Halton Hills", "Caledon", "Innisfil",
      "Orangeville", "Alliston", "Owen Sound", "Kincardine", "Goderich", "Cobourg", "Port Hope", "Lindsay",
      "Kawartha Lakes", "Brockville", "Pembroke", "Petawawa", "Kanata", "Nepean", "Orleans|Orléans", "Gloucester",
      "Leamington", "Tecumseh", "LaSalle", "Amherstburg", "Strathroy", "St Thomas|Saint Thomas", "Tillsonburg",
      "Ingersoll", "Simcoe", "Port Colborne", "Fort Erie", "Thorold", "Waterdown", "Milton", "Uxbridge",
      "Stouffville|Whitchurch-Stouffville", "Aurora", "King City", "Bradford West Gwillimbury", "Barrhaven",
      "Sherwood Park", "St Albert|Saint Albert", "Spruce Grove", "Leduc", "Okotoks", "Cochrane", "Canmore",
      "Banff", "Jasper", "Lloydminster", "Camrose", "Wetaskiwin", "Brooks", "Strathmore", "Chestermere",
      "Swift Current", "Yorkton", "North Battleford", "Estevan", "Weyburn", "Portage la Prairie", "Steinbach",
      "Thompson", "Selkirk", "Winkler", "Morden", "Vernon", "Penticton", "Kelowna", "West Kelowna",
      "Courtenay", "Campbell River", "Duncan", "Parksville", "Port Alberni", "Powell River", "Prince Rupert",
      "Terrace", "Fort St John|Fort Saint John", "Dawson Creek", "Cranbrook", "Nelson", "Trail", "Castlegar",
      "Salmon Arm", "Williams Lake", "Quesnel", "Mission", "Pitt Meadows", "Port Moody", "Ladner", "Tsawwassen",
      "Bedford", "Sackville", "Wolfville", "Kentville", "Bridgewater", "Yarmouth", "Antigonish", "New Glasgow",
      "Amherst", "Riverview", "Dieppe", "Miramichi", "Edmundston", "Campbellton", "Summerside", "Stratford",
      "Mount Pearl", "Corner Brook", "Gander", "Grand Falls-Windsor|Grand Falls Windsor", "Labrador City",
      "Happy Valley-Goose Bay|Goose Bay",
    ],
    metros: [
      "Greater Toronto Area|Greater Toronto|GTA", "Greater Montreal|Grand Montréal|Grand Montreal",
      "Greater Vancouver|Metro Vancouver", "Lower Mainland", "Kitchener-Waterloo", "Region of Waterloo|Waterloo Region",
      "Golden Horseshoe", "Durham Region", "Peel Region", "York Region", "Halton Region", "Niagara Region", "Okanagan",
      "National Capital Region", "Greater Sudbury Area", "Greater Halifax", "Halifax Regional Municipality|HRM",
      "Metro Calgary|Calgary Region", "Metro Edmonton|Edmonton Metropolitan Region", "Capital Region",
      "Fraser Valley", "Vancouver Island", "Greater Victoria", "Atlantic Canada", "Maritimes", "Prairies",
      "Western Canada", "Eastern Canada", "Northern Ontario", "Southwestern Ontario", "Eastern Ontario",
      "Ottawa-Gatineau|Ottawa Gatineau", "Montérégie|Monteregie", "Laurentides|Laurentians", "Estrie|Eastern Townships",
      "Mauricie", "Outaouais", "Gaspésie|Gaspesie", "Côte-Nord|Cote Nord", "Abitibi", "Bas-Saint-Laurent|Bas Saint Laurent",
      "Saguenay-Lac-Saint-Jean|Saguenay Lac Saint Jean", "Chaudière-Appalaches|Chaudiere Appalaches",
      "Tri-Cities BC", "North Shore Vancouver", "Kootenays", "Cariboo", "Peace Region", "Thompson-Okanagan|Thompson Okanagan",
    ],
  },
  AU: {
    regions: [
      "New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania",
      "Australian Capital Territory", "Northern Territory",
    ],
    regionCodes: ["NSW", "VIC", "QLD", "WA", "SA", "TAS", "ACT", "NT"],
    cities: [
      "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle",
      "Wollongong", "Sunshine Coast", "Hobart", "Geelong", "Townsville", "Cairns", "Toowoomba", "Darwin",
      "Ballarat", "Bendigo", "Albury|Albury-Wodonga|Albury Wodonga", "Wodonga", "Launceston", "Mackay",
      "Rockhampton", "Bunbury", "Bundaberg", "Coffs Harbour", "Wagga Wagga|Wagga", "Hervey Bay", "Mildura",
      "Shepparton", "Gladstone", "Port Macquarie", "Tamworth", "Dubbo", "Geraldton", "Nowra", "Bathurst",
      "Warrnambool", "Kalgoorlie", "Alice Springs", "Broome", "Mount Gambier", "Lismore", "Armidale",
      "Whyalla", "Devonport", "Burnie", "Traralgon", "Morwell", "Bairnsdale", "Sale", "Horsham", "Wangaratta",
      "Echuca", "Swan Hill", "Griffith", "Goulburn", "Bowral", "Queanbeyan", "Orange NSW", "Mudgee",
      "Broken Hill", "Byron Bay", "Tweed Heads", "Ballina", "Grafton", "Taree", "Forster", "Maitland",
      "Cessnock", "Singleton", "Muswellbrook", "Gosford", "Wyong", "Tuggerah", "Erina", "Katoomba",
      "Penrith", "Parramatta", "Liverpool", "Blacktown", "Campbelltown", "Camden NSW", "Bankstown",
      "Hurstville", "Sutherland", "Cronulla", "Miranda", "Kogarah", "Rockdale", "Mascot", "Botany",
      "Randwick", "Bondi", "Bondi Junction", "Double Bay", "Manly", "Dee Why", "Brookvale", "Frenchs Forest",
      "Hornsby", "Ryde", "Macquarie Park", "North Ryde", "Chatswood", "St Leonards|Saint Leonards",
      "North Sydney", "Crows Nest", "Artarmon", "Lane Cove", "Epping", "Castle Hill", "Norwest", "Baulkham Hills",
      "Bella Vista", "Rhodes", "Olympic Park|Sydney Olympic Park", "Homebush", "Strathfield", "Burwood",
      "Ashfield", "Marrickville", "Newtown", "Alexandria NSW", "Redfern", "Surry Hills", "Pyrmont",
      "Ultimo", "Barangaroo", "Darling Harbour", "Haymarket", "Circular Quay", "The Rocks", "Zetland",
      "Waterloo NSW", "Rosebery", "Eveleigh", "Chippendale", "Glebe", "Leichhardt", "Balmain",
      "Docklands", "Southbank", "South Melbourne", "Port Melbourne", "St Kilda|Saint Kilda", "Richmond",
      "Cremorne", "Abbotsford", "Collingwood", "Fitzroy", "Carlton", "Brunswick", "Coburg", "Preston",
      "Northcote", "Thornbury", "Heidelberg", "Bundoora", "Doncaster", "Box Hill", "Ringwood", "Hawthorn",
      "Camberwell", "Kew", "Malvern", "Prahran", "South Yarra", "Toorak", "Brighton", "Caulfield", "Moorabbin",
      "Cheltenham", "Mentone", "Frankston", "Dandenong", "Clayton", "Mulgrave", "Notting Hill", "Glen Waverley",
      "Mount Waverley", "Burwood East", "Nunawading", "Bayswater", "Knox", "Scoresby", "Rowville", "Berwick",
      "Cranbourne", "Pakenham", "Werribee", "Point Cook", "Sunshine", "Footscray", "Essendon", "Tullamarine",
      "Broadmeadows", "Craigieburn", "Epping VIC", "Mernda", "Sunbury", "Melton", "Laverton", "Altona",
      "Williamstown", "Fortitude Valley", "Newstead", "Teneriffe", "Bowen Hills", "Spring Hill", "Milton QLD",
      "Toowong", "Indooroopilly", "St Lucia|Saint Lucia", "West End", "South Brisbane", "Woolloongabba",
      "Kangaroo Point", "Hamilton QLD", "Ascot", "Chermside", "Eight Mile Plains", "Upper Mount Gravatt",
      "Mount Gravatt", "Sunnybank", "Springwood", "Logan", "Beenleigh", "Ipswich", "Springfield QLD",
      "Redcliffe", "Caboolture", "North Lakes", "Strathpine", "Cleveland QLD", "Capalaba", "Wynnum",
      "Southport", "Surfers Paradise", "Broadbeach", "Robina", "Varsity Lakes", "Burleigh Heads", "Coolangatta",
      "Nerang", "Helensvale", "Coomera", "Maroochydore", "Caloundra", "Noosa", "Nambour", "Kawana",
      "Fremantle", "Joondalup", "Subiaco", "West Perth", "East Perth", "Osborne Park", "Malaga", "Balcatta",
      "Belmont WA", "Welshpool", "Canning Vale", "Bibra Lake", "Cockburn", "Rockingham", "Mandurah",
      "Midland", "Armadale", "Cannington", "Victoria Park", "Burswood", "Nedlands", "Claremont", "Cottesloe",
      "Scarborough WA", "Wanneroo", "Ellenbrook", "Kwinana", "Bunbury", "Busselton", "Margaret River",
      "Albany", "Esperance", "Karratha", "Port Hedland", "Newman", "Tom Price", "Glenelg", "Norwood",
      "Mawson Lakes", "Elizabeth", "Salisbury", "Modbury", "Tea Tree Gully", "Marion", "Noarlunga",
      "Mount Barker", "Port Adelaide", "Prospect", "Unley", "Kent Town", "Tonsley", "Bedford Park",
      "Belconnen", "Woden", "Tuggeranong", "Fyshwick", "Gungahlin", "Barton", "Braddon", "Kingston",
      "Deakin", "Bruce", "Mitchell", "Hume", "Symonston", "Palmerston NT", "Casuarina", "Katherine",
      "Nhulunbuy", "Tennant Creek", "Kingston TAS", "Glenorchy", "Clarence", "Sandy Bay", "Moonah",
      "Bellerive", "Ulverstone", "Wynyard", "Smithton",
    ],
    metros: [
      "Greater Sydney", "Greater Melbourne", "Greater Brisbane", "Greater Perth", "Greater Adelaide",
      "Greater Hobart", "Greater Darwin", "South East Queensland|SEQ", "Illawarra", "Hunter Region|Hunter Valley|Hunter",
      "Northern Rivers", "Riverina", "Gippsland", "Barossa|Barossa Valley", "Pilbara", "Goldfields WA",
      "Central Coast NSW", "Western Sydney", "Inner West", "Sydney CBD", "Melbourne CBD", "Brisbane CBD",
      "Perth CBD", "Adelaide CBD", "Northern Beaches", "Eastern Suburbs", "Hills District", "Sutherland Shire",
      "Macarthur", "Blue Mountains", "Mornington Peninsula", "Yarra Valley", "Latrobe Valley", "Geelong Region",
      "Bellarine", "Surf Coast", "Wimmera", "Mallee", "Goulburn Valley", "Darling Downs", "Wide Bay",
      "Fraser Coast", "Whitsundays", "Far North Queensland", "North Queensland", "Central Queensland",
      "Moreton Bay", "Redlands", "Ipswich Region", "Great Southern", "South West WA", "Wheatbelt",
      "Mid West WA", "Kimberley WA", "Fleurieu Peninsula", "Adelaide Hills", "Eyre Peninsula", "Yorke Peninsula",
      "Limestone Coast", "Riverland", "Top End", "Red Centre", "Central Australia", "Tasman Peninsula",
      "North West Tasmania", "Regional NSW", "Regional Victoria", "Regional Queensland", "Regional WA",
      "Regional SA", "Regional Australia",
    ],
  },
  GB: {
    regions: [
      "England", "Scotland", "Wales", "Northern Ireland",
      "Greater London", "Greater Manchester", "West Midlands", "West Yorkshire", "South Yorkshire", "North Yorkshire",
      "East Riding of Yorkshire|East Riding", "Yorkshire", "Merseyside", "Tyne and Wear", "Berkshire", "Hampshire",
      "Surrey", "Kent", "Essex", "Hertfordshire", "Oxfordshire", "Cambridgeshire", "Buckinghamshire", "Bedfordshire",
      "Wiltshire", "Somerset", "Devon", "Cornwall", "Dorset", "Gloucestershire", "Warwickshire", "Leicestershire",
      "Nottinghamshire", "Derbyshire", "Staffordshire", "Cheshire", "Lancashire", "Cumbria", "Northumberland",
      "County Durham", "Durham", "East Sussex", "West Sussex", "Sussex", "Norfolk", "Suffolk", "Lincolnshire",
      "Shropshire", "Herefordshire", "Worcestershire", "Northamptonshire", "Rutland", "Isle of Wight",
      "Fife", "Lothian", "Midlothian", "West Lothian", "East Lothian", "Lanarkshire", "North Lanarkshire",
      "South Lanarkshire", "Renfrewshire", "Ayrshire", "Aberdeenshire", "Perthshire", "Perth and Kinross",
      "Stirlingshire", "Dumfries and Galloway", "Argyll and Bute", "Moray", "Scottish Borders", "Scottish Highlands",
      "Gwynedd", "Powys", "Ceredigion", "Conwy", "Flintshire", "Denbighshire", "Anglesey", "Glamorgan",
      "Vale of Glamorgan", "Monmouthshire", "Pembrokeshire", "Carmarthenshire", "Rhondda Cynon Taf",
      "County Antrim|Antrim", "County Down", "County Armagh|Armagh", "County Tyrone|Tyrone", "County Fermanagh|Fermanagh",
      "County Londonderry|County Derry",
    ],
    regionCodes: [],
    cities: [
      "London", "Birmingham", "Manchester", "Leeds", "Glasgow", "Edinburgh", "Liverpool", "Bristol", "Sheffield",
      "Newcastle upon Tyne|Newcastle-upon-Tyne", "Newcastle", "Nottingham", "Leicester", "Coventry", "Bradford",
      "Cardiff", "Belfast", "Southampton", "Portsmouth", "Brighton", "Brighton and Hove", "Hove", "Plymouth",
      "Reading", "Milton Keynes", "Cambridge", "Oxford", "Bath", "York", "Exeter", "Norwich", "Ipswich", "Derby",
      "Stoke-on-Trent|Stoke on Trent|Stoke", "Wolverhampton", "Sunderland", "Middlesbrough", "Kingston upon Hull|Hull",
      "Swansea", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth", "Luton", "Slough", "Watford",
      "Basingstoke", "Guildford", "Woking", "Crawley", "Maidenhead", "Bracknell", "Swindon", "Cheltenham",
      "Gloucester", "Bournemouth", "Poole", "Salisbury", "Winchester", "Chichester", "Worthing", "Eastbourne",
      "Hastings", "Canterbury", "Maidstone", "Ashford", "Dartford", "Croydon", "Bromley", "Kingston upon Thames|Kingston-upon-Thames",
      "Kingston", "Richmond upon Thames|Richmond-upon-Thames", "Richmond", "Wimbledon", "Twickenham", "Hounslow",
      "Ealing", "Harrow", "Uxbridge", "Wembley", "Stratford", "Shoreditch", "Hoxton", "Clerkenwell", "Farringdon",
      "Holborn", "Soho", "Mayfair", "Marylebone", "Paddington", "Kensington", "Chelsea", "Fulham", "Hammersmith",
      "Chiswick", "Battersea", "Vauxhall", "Southwark", "Bermondsey", "London Bridge", "Liverpool Street",
      "Kings Cross|King's Cross", "Euston", "Camden", "Islington", "Hackney", "Greenwich", "Docklands", "Westminster",
      "Wandsworth", "Lewisham", "Brixton", "Clapham", "Putney", "Sutton", "Barnet", "Enfield", "Ilford", "Romford",
      "Dagenham", "Woolwich", "Heathrow", "Gatwick", "Stansted", "St Albans|Saint Albans", "Hemel Hempstead",
      "Stevenage", "Welwyn Garden City", "Hatfield", "Harlow", "Chelmsford", "Colchester", "Southend|Southend-on-Sea|Southend on Sea",
      "Basildon", "Brentwood", "Bedford", "Northampton", "Kettering", "Corby", "Peterborough", "Huntingdon", "Ely",
      "Newmarket", "Bury St Edmunds|Bury Saint Edmunds", "Lowestoft", "Great Yarmouth", "Kings Lynn|King's Lynn",
      "Lincoln", "Grimsby", "Scunthorpe", "Doncaster", "Rotherham", "Barnsley", "Wakefield", "Huddersfield",
      "Halifax", "Harrogate", "Scarborough", "Stockton-on-Tees|Stockton on Tees", "Darlington", "Hartlepool",
      "Gateshead", "South Shields", "Carlisle", "Kendal", "Lancaster", "Preston", "Blackpool", "Blackburn",
      "Burnley", "Bolton", "Bury", "Wigan", "Warrington", "Widnes", "Runcorn", "St Helens|Saint Helens",
      "Southport", "Birkenhead", "Wirral", "Chester", "Crewe", "Macclesfield", "Stockport", "Oldham", "Rochdale",
      "Salford", "Trafford", "Altrincham", "Sale", "Wilmslow", "Knutsford", "Stafford", "Telford", "Shrewsbury",
      "Hereford", "Worcester", "Kidderminster", "Redditch", "Bromsgrove", "Solihull", "Dudley", "Walsall",
      "West Bromwich", "Sutton Coldfield", "Tamworth", "Lichfield", "Burton upon Trent|Burton on Trent",
      "Nuneaton", "Leamington Spa|Royal Leamington Spa|Leamington", "Warwick", "Stratford-upon-Avon|Stratford upon Avon",
      "Loughborough", "Chesterfield", "Mansfield", "Newark", "Grantham", "Boston", "Skegness", "Northwich",
      "Wrexham", "Bangor", "Llandudno", "Aberystwyth", "Carmarthen", "Llanelli", "Neath", "Port Talbot",
      "Bridgend", "Pontypridd", "Merthyr Tydfil", "Caerphilly", "Cwmbran", "Newport", "Abergavenny", "Monmouth",
      "Chepstow", "Paisley", "East Kilbride", "Livingston", "Cumbernauld", "Hamilton", "Motherwell", "Kilmarnock",
      "Ayr", "Irvine", "Greenock", "Dunfermline", "Kirkcaldy", "Falkirk", "Dumfries", "Elgin", "Fort William",
      "Oban", "Lisburn", "Newry", "Newtownabbey", "Carrickfergus", "Ballymena", "Coleraine", "Omagh", "Enniskillen",
      "Craigavon", "Lurgan", "Portadown", "Derry|Londonderry", "Epping", "Horsham", "Malvern", "Penrith",
      "Bayswater", "Camberwell", "Kew", "Notting Hill", "Haymarket", "Newstead", "Ascot", "Welshpool",
      "Cranbrook", "Yarmouth", "Pembroke", "Berwick|Berwick-upon-Tweed", "Melton Mowbray", "West End", "Windsor",
      "Eton", "Egham", "Staines", "Weybridge", "Leatherhead", "Epsom", "Redhill", "Reigate", "Dorking",
    ],
    metros: [
      "Tyneside", "Teesside", "Humberside", "Thames Valley", "Home Counties", "M4 Corridor", "Silicon Fen",
      "City of London|Square Mile", "Canary Wharf", "North West England", "North East England", "South West England",
      "South East England", "East of England", "East Anglia", "East Midlands", "West Country", "Central Belt",
      "South Wales", "North Wales", "Mid Wales", "West Wales", "Black Country", "Potteries", "Peak District",
      "Lake District", "Cotswolds", "Midlands", "Northern England", "Southern England", "Central London",
      "North London", "South London", "East London", "West London", "Greater Glasgow", "Greater Belfast",
      "Greater Bristol", "Greater Nottingham", "Greater Cambridge", "Oxford-Cambridge Arc|Oxford Cambridge Arc",
    ],
  },
  IN: {
    regions: [
      "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana",
      "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
      "Meghalaya", "Mizoram", "Nagaland", "Odisha|Orissa", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu|Tamilnadu",
      "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand|Uttaranchal", "West Bengal",
      "Andaman and Nicobar Islands|Andaman and Nicobar", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu|Dadra and Nagar Haveli|Daman and Diu",
      "Delhi|NCT of Delhi|National Capital Territory of Delhi", "Jammu and Kashmir|Jammu & Kashmir", "Ladakh",
      "Lakshadweep", "Puducherry|Pondicherry",
    ],
    // Only codes postings actually use. Codes that collide with US/CA state
    // codes nobody writes for India (GA, OR, LA, NL, SK, CT, AR, AS, MN) are
    // left out so the US/CA reading keeps working; TN is kept because both
    // "Chennai, TN" and "Nashville, TN" are common.
    regionCodes: [
      "KA", "MH", "TN", "TS", "TG", "DL", "UP", "HR", "GJ", "WB", "KL", "RJ", "AP", "MP", "PB", "OD", "BR",
      "JH", "CG", "HP", "CH", "PY", "JK",
    ],
    cities: [
      "Mumbai|Bombay", "New Delhi", "Bengaluru|Bangalore", "Hyderabad", "Ahmedabad", "Chennai|Madras",
      "Kolkata|Calcutta", "Surat", "Pune|Poona", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane",
      "Bhopal", "Visakhapatnam|Vizag|Vishakhapatnam", "Pimpri-Chinchwad|Pimpri Chinchwad|Pimpri", "Patna",
      "Vadodara|Baroda", "Ghaziabad", "Ludhiana", "Agra", "Nashik|Nasik", "Faridabad", "Meerut", "Rajkot",
      "Varanasi|Benares", "Srinagar", "Aurangabad|Chhatrapati Sambhajinagar", "Dhanbad", "Amritsar", "Navi Mumbai",
      "Prayagraj|Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur", "Gwalior", "Vijayawada", "Jodhpur",
      "Madurai", "Raipur", "Kota", "Guwahati", "Solapur", "Hubli|Hubballi", "Hubli-Dharwad|Hubballi-Dharwad",
      "Dharwad", "Mysuru|Mysore", "Tiruchirappalli|Trichy|Tiruchirapalli", "Bareilly", "Aligarh", "Tiruppur|Tirupur",
      "Moradabad", "Jalandhar", "Bhubaneswar|Bhubaneshwar", "Salem", "Warangal", "Guntur", "Bhiwandi",
      "Saharanpur", "Gorakhpur", "Bikaner", "Amravati", "Noida", "Greater Noida", "Jamshedpur", "Bhilai",
      "Cuttack", "Firozabad", "Kochi|Cochin", "Nellore", "Bhavnagar", "Dehradun", "Durgapur", "Asansol",
      "Rourkela", "Nanded", "Kolhapur", "Ajmer", "Akola", "Kalaburagi|Gulbarga", "Jamnagar", "Ujjain", "Siliguri",
      "Jhansi", "Ulhasnagar", "Jammu", "Sangli", "Mangaluru|Mangalore", "Erode", "Belagavi|Belgaum", "Ambattur",
      "Tirunelveli", "Malegaon", "Udaipur", "Thiruvananthapuram|Trivandrum", "Kozhikode|Calicut", "Thrissur|Trichur",
      "Kollam|Quilon", "Gurugram|Gurgaon", "Mohali|SAS Nagar|Sahibzada Ajit Singh Nagar", "Panchkula", "Panaji|Panjim",
      "Shimla", "Manesar", "Vellore", "Hosur", "Kakinada", "Tirupati", "Anand", "Gandhinagar", "Rajahmundry",
      "Kharagpur", "Roorkee", "Kanchipuram", "Karnal", "Ambala", "Hisar", "Rohtak", "Sonipat|Sonepat", "Bhiwadi",
      "Dharamshala|Dharamsala", "Haridwar", "Rishikesh", "Mathura", "Vrindavan", "Bhagalpur", "Muzaffarpur",
      "Gaya", "Darbhanga", "Bokaro|Bokaro Steel City", "Hazaribagh", "Sambalpur", "Berhampur|Brahmapur",
      "Puri", "Imphal", "Shillong", "Aizawl", "Agartala", "Kohima", "Dimapur", "Itanagar", "Gangtok", "Dibrugarh",
      "Silchar", "Jorhat", "Tezpur", "Nagaon", "Thanjavur", "Dindigul", "Karur", "Namakkal", "Thoothukudi|Tuticorin",
      "Nagercoil", "Kanyakumari", "Cuddalore", "Pondicherry", "Hosur", "Krishnagiri", "Chittoor", "Anantapur",
      "Kurnool", "Kadapa", "Ongole", "Eluru", "Bhimavaram", "Machilipatnam", "Srikakulam", "Vizianagaram",
      "Karimnagar", "Nizamabad", "Khammam", "Mahbubnagar", "Nalgonda", "Secunderabad", "Cyberabad",
      "Davanagere|Davangere", "Shivamogga|Shimoga", "Tumakuru|Tumkur", "Ballari|Bellary", "Vijayapura|Bijapur",
      "Udupi", "Manipal", "Hassan", "Mandya", "Chikkamagaluru|Chikmagalur", "Kolar", "Raichur", "Bidar",
      "Alappuzha|Alleppey", "Kottayam", "Kannur|Cannanore", "Palakkad|Palghat", "Malappuram", "Pathanamthitta",
      "Idukki", "Wayanad", "Kasaragod", "Ernakulam", "Kakkanad", "Infopark", "Technopark", "Aurangabad",
      "Latur", "Ahmednagar|Ahilyanagar", "Jalgaon", "Dhule", "Satara", "Ratnagiri", "Chandrapur", "Wardha",
      "Yavatmal", "Gondia", "Palghar", "Vasai|Vasai-Virar|Virar", "Kalyan|Kalyan-Dombivli", "Dombivli", "Badlapur",
      "Panvel", "Kharghar", "Vashi", "Belapur|CBD Belapur", "Airoli", "Ghansoli", "Andheri", "Bandra", "Powai",
      "Goregaon", "Malad", "Borivali", "Kandivali", "Dadar", "Worli", "Lower Parel", "Parel", "Byculla",
      "Colaba", "Nariman Point", "Fort Mumbai", "Churchgate", "Chembur", "Ghatkopar", "Vikhroli", "Mulund",
      "Bhandup", "Kurla", "Santacruz", "Vile Parle", "Juhu", "Versova", "Hinjewadi|Hinjawadi", "Magarpatta",
      "Kharadi", "Wakad", "Baner", "Aundh", "Viman Nagar", "Kalyani Nagar", "Koregaon Park", "Hadapsar",
      "Kothrud", "Shivajinagar", "Pimple Saudagar", "Wagholi", "Talegaon", "Chakan", "Koramangala", "Indiranagar",
      "Whitefield", "Marathahalli", "Bellandur", "Sarjapur|Sarjapur Road", "HSR Layout|HSR", "BTM Layout|BTM",
      "Jayanagar", "JP Nagar", "Bannerghatta|Bannerghatta Road", "Electronic City|Electronics City", "Hebbal",
      "Yelahanka", "Yeshwanthpur", "Malleshwaram|Malleswaram", "Rajajinagar", "MG Road", "Domlur", "Mahadevapura",
      "KR Puram", "Hoodi", "Brookefield", "Kadubeesanahalli", "Bommanahalli", "Hosur Road", "Devanahalli",
      "Gachibowli", "Madhapur", "HITEC City|Hitech City|Hi-Tech City|HITECH City", "Kondapur", "Kukatpally",
      "Jubilee Hills", "Banjara Hills", "Begumpet", "Ameerpet", "Manikonda", "Nanakramguda", "Financial District",
      "Raidurg", "Kokapet", "Miyapur", "Uppal", "Pocharam", "Sholinganallur", "Perungudi", "Taramani", "Guindy",
      "Velachery", "OMR|Old Mahabalipuram Road", "Siruseri", "Porur", "Ambattur", "Anna Nagar", "T Nagar", "Adyar",
      "Nungambakkam", "Egmore", "Mylapore", "Tambaram", "Chromepet", "Pallavaram", "Poonamallee", "Oragadam",
      "Sriperumbudur", "Salt Lake Sector V|Sector V|Sector 5 Salt Lake", "Salt Lake City Kolkata|Bidhannagar",
      "Rajarhat", "New Town Kolkata|Newtown Kolkata", "Park Street", "Cyber City|DLF Cyber City|Cybercity",
      "Golf Course Road", "Sohna Road", "Udyog Vihar", "Sector 62 Noida", "Sector 18 Noida", "Sector 16 Noida",
      "Connaught Place", "Nehru Place", "Okhla", "Saket", "Hauz Khas", "Dwarka", "Rohini", "Janakpuri",
      "Aerocity", "Vasant Kunj", "Lajpat Nagar", "Karol Bagh", "Greater Kailash", "Mayur Vihar", "Laxmi Nagar",
      "Pitampura", "Rajouri Garden", "Ashram Road", "SG Highway", "Prahlad Nagar", "Satellite", "Bopal",
      "Vastrapur", "Navrangpura", "Maninagar", "GIFT City", "Vapi", "Ankleshwar", "Bharuch", "Navsari", "Valsad",
      "Silvassa", "Daman", "Diu", "Port Blair", "Kavaratti", "Leh", "Kargil",
    ],
    metros: [
      "Delhi NCR|NCR Delhi|Delhi-NCR|Delhi National Capital Region", "National Capital Region", "NCR",
      "Mumbai Metropolitan Region|MMR", "Greater Mumbai", "Greater Bengaluru|Greater Bangalore", "Greater Hyderabad",
      "Greater Chennai", "Greater Kolkata", "Bengaluru Urban|Bangalore Urban", "Bengaluru Rural|Bangalore Rural",
      "Pune Metropolitan Region|PMR", "Chandigarh Tricity|Tricity", "Kochi Metro", "Konkan", "Vidarbha",
      "Marathwada", "Malwa", "Bundelkhand", "Saurashtra", "Kutch|Kachchh", "Malabar", "Coastal Karnataka",
      "Rayalaseema", "Coastal Andhra", "Telangana Region", "Chota Nagpur", "Doab", "Terai", "Kashmir Valley",
      "North East India|Northeast India", "South India", "North India", "West India", "East India", "Central India",
      "Pan India|Pan-India|PAN India", "Anywhere in India", "Across India",
    ],
  },
  SG: {
    // City-state: "Singapore" itself is an explicit country label handled by
    // country-evidence.ts. Planning areas, districts and business parks are the
    // only sub-national names postings use; generic words (Stadium, Expo,
    // Promenade, Pioneer …) are deliberately left out.
    regions: [
      "Central Region Singapore", "East Region Singapore", "North Region Singapore",
      "North-East Region Singapore|North East Region Singapore", "West Region Singapore",
    ],
    regionCodes: [],
    cities: [
      "Jurong|Jurong East|Jurong West", "Changi", "Tampines", "Woodlands", "Bukit Timah", "Orchard|Orchard Road",
      "Raffles Place", "Marina Bay", "One-North|One North|Onenorth", "Tanjong Pagar", "Paya Lebar", "Kallang",
      "Toa Payoh", "Ang Mo Kio", "Bishan", "Queenstown", "Clementi", "Bedok", "Punggol", "Sengkang", "Yishun",
      "Serangoon", "Pasir Ris", "Tuas", "Bugis", "Novena", "HarbourFront|Harbourfront|Harbour Front", "Sentosa",
      "Buona Vista", "Tiong Bahru", "Outram", "Shenton Way", "Suntec|Suntec City", "Changi Business Park",
      "Seletar", "Kranji", "Bukit Merah", "Bukit Batok", "Bukit Panjang", "Choa Chu Kang", "Hougang", "Geylang",
      "Boon Lay", "Tanglin", "Rochor", "Downtown Core", "Marina South", "River Valley", "Holland Village",
      "Dover", "Kent Ridge", "Mapletree Business City", "Singapore Science Park|Science Park Singapore",
      "Pasir Panjang", "Telok Blangah", "Jurong Island", "Sembawang", "Yio Chu Kang", "Tai Seng",
      "MacPherson|Macpherson", "Katong", "Joo Chiat", "Marine Parade", "Newton", "Somerset", "Dhoby Ghaut",
      "Clarke Quay", "Boat Quay", "Robertson Quay", "Kampong Glam", "Farrer Park", "Aljunied", "Potong Pasir",
      "Balestier", "Telok Ayer", "Duxton", "Tanjong Rhu", "Changi Airport", "Changi Village",
      "Gardens by the Bay", "Marina Bay Sands|MBS", "Ubi", "Eunos", "Simei", "Bayfront", "Redhill",
    ],
    metros: [
      "Singapore CBD|Singapore Central Business District", "Jurong Lake District", "Jurong Innovation District",
      "Punggol Digital District", "Biopolis", "Fusionopolis", "Mediapolis", "Cleantech Park", "Tuas Biomedical Park",
      "Seletar Aerospace Park", "Marina Bay Financial Centre|MBFC", "Asia Square", "Raffles Quay",
      "Tanjong Pagar Centre|Guoco Tower", "Paya Lebar Quarter|PLQ", "Alexandra Technopark", "Kent Ridge Research Park",
      "Tampines Regional Centre", "Woodlands Regional Centre", "Changi North",
    ],
  },
  JP: {
    regions: [
      "Hokkaido|北海道", "Aomori|青森|青森県", "Iwate|岩手|岩手県", "Miyagi|宮城|宮城県", "Akita|秋田|秋田県",
      "Yamagata|山形|山形県", "Fukushima|福島|福島県", "Ibaraki|茨城|茨城県", "Tochigi|栃木|栃木県", "Gunma|群馬|群馬県",
      "Saitama|埼玉|埼玉県", "Chiba|千葉|千葉県", "Tokyo|東京|東京都|Tokyo Metropolis|Tokyo-to", "Kanagawa|神奈川|神奈川県",
      "Niigata|新潟|新潟県", "Toyama|富山|富山県", "Ishikawa|石川|石川県", "Fukui|福井|福井県", "Yamanashi|山梨|山梨県",
      "Nagano|長野|長野県", "Gifu|岐阜|岐阜県", "Shizuoka|静岡|静岡県", "Aichi|愛知|愛知県", "Mie|三重|三重県",
      "Shiga|滋賀|滋賀県", "Kyoto|京都|京都府", "Osaka|大阪|大阪府|Ōsaka", "Hyogo|兵庫|兵庫県|Hyōgo", "Nara|奈良|奈良県",
      "Wakayama|和歌山|和歌山県", "Tottori|鳥取|鳥取県", "Shimane|島根|島根県", "Okayama|岡山|岡山県",
      "Hiroshima|広島|広島県", "Yamaguchi|山口|山口県", "Tokushima|徳島|徳島県", "Kagawa|香川|香川県",
      "Ehime|愛媛|愛媛県", "Kochi|高知|高知県|Kōchi", "Fukuoka|福岡|福岡県", "Saga|佐賀|佐賀県", "Nagasaki|長崎|長崎県",
      "Kumamoto|熊本|熊本県", "Oita|大分|大分県|Ōita", "Miyazaki|宮崎|宮崎県", "Kagoshima|鹿児島|鹿児島県",
      "Okinawa|沖縄|沖縄県",
    ],
    regionCodes: [],
    cities: [
      "Yokohama|横浜|横浜市", "Osaka City|大阪市", "Nagoya|名古屋|名古屋市", "Sapporo|札幌|札幌市", "Fukuoka City|福岡市",
      "Kobe|神戸|神戸市|Kōbe", "Kawasaki|川崎|川崎市", "Kyoto City|京都市", "Saitama City|さいたま|さいたま市",
      "Hiroshima City|広島市", "Sendai|仙台|仙台市", "Chiba City|千葉市", "Kitakyushu|北九州|北九州市", "Sakai|堺|堺市",
      "Niigata City|新潟市", "Hamamatsu|浜松|浜松市", "Kumamoto City|熊本市", "Sagamihara|相模原|相模原市",
      "Okayama City|岡山市", "Shizuoka City|静岡市", "Funabashi|船橋|船橋市", "Kagoshima City|鹿児島市",
      "Kawaguchi|川口|川口市", "Hachioji|八王子|八王子市|Hachiōji", "Himeji|姫路|姫路市", "Matsuyama|松山|松山市",
      "Utsunomiya|宇都宮|宇都宮市", "Matsudo|松戸|松戸市", "Nishinomiya|西宮|西宮市", "Oita City|大分市",
      "Kurashiki|倉敷|倉敷市", "Kanazawa|金沢|金沢市", "Fukuyama|福山|福山市", "Amagasaki|尼崎|尼崎市",
      "Ichikawa|市川|市川市", "Nagasaki City|長崎市", "Toyota|豊田|豊田市|Toyota City", "Takamatsu|高松|高松市",
      "Toyama City|富山市", "Nara City|奈良市", "Gifu City|岐阜市", "Machida|町田|町田市", "Iwaki|いわき|いわき市",
      "Koriyama|郡山|郡山市|Kōriyama", "Fujisawa|藤沢|藤沢市", "Kashiwa|柏|柏市", "Takasaki|高崎|高崎市",
      "Yokosuka|横須賀|横須賀市", "Toyohashi|豊橋|豊橋市", "Nagano City|長野市", "Okazaki|岡崎|岡崎市",
      "Kawagoe|川越|川越市", "Akita City|秋田市", "Naha|那覇|那覇市", "Kochi City|高知市", "Tsukuba|つくば|つくば市",
      "Mito|水戸|水戸市", "Morioka|盛岡|盛岡市", "Aomori City|青森市", "Yamagata City|山形市", "Fukushima City|福島市",
      "Otsu|大津|大津市|Ōtsu", "Wakayama City|和歌山市", "Tottori City|鳥取市", "Matsue|松江|松江市",
      "Yamaguchi City|山口市", "Tokushima City|徳島市", "Saga City|佐賀市", "Miyazaki City|宮崎市", "Fukui City|福井市",
      "Maebashi|前橋|前橋市", "Kofu|甲府|甲府市|Kōfu", "Tsu|津市", "Chofu|調布|調布市|Chōfu", "Tachikawa|立川|立川市",
      "Fuchu|府中|府中市|Fuchū", "Musashino|武蔵野|武蔵野市", "Mitaka|三鷹|三鷹市", "Atsugi|厚木|厚木市",
      "Odawara|小田原|小田原市", "Numazu|沼津|沼津市", "Fuji City|富士市", "Suita|吹田|吹田市", "Toyonaka|豊中|豊中市",
      "Takatsuki|高槻|高槻市", "Hirakata|枚方|枚方市", "Higashiosaka|東大阪|東大阪市|Higashi-Osaka|Higashiōsaka",
      "Ichinomiya|一宮|一宮市", "Kasugai|春日井|春日井市", "Toyokawa|豊川|豊川市", "Kure|呉|呉市",
      "Shimonoseki|下関|下関市", "Kurume|久留米|久留米市", "Nagaoka|長岡|長岡市", "Joetsu|上越|上越市|Jōetsu",
      "Hakodate|函館|函館市", "Asahikawa|旭川|旭川市", "Kushiro|釧路|釧路市", "Obihiro|帯広|帯広市",
      "Tomakomai|苫小牧|苫小牧市", "Ishinomaki|石巻|石巻市", "Hitachi|日立市", "Akashi|明石|明石市",
      "Shibuya|渋谷|渋谷区", "Shinjuku|新宿|新宿区", "Minato|港区|Minato-ku|Minato City", "Chiyoda|千代田|千代田区",
      "Chuo|中央区|Chūō|Chuo-ku", "Shinagawa|品川|品川区", "Roppongi|六本木", "Marunouchi|丸の内", "Otemachi|大手町|Ōtemachi",
      "Meguro|目黒|目黒区", "Ebisu|恵比寿", "Akihabara|秋葉原", "Ikebukuro|池袋", "Toshima|豊島区", "Bunkyo|文京区|Bunkyō",
      "Setagaya|世田谷|世田谷区", "Nakano|中野区", "Suginami|杉並|杉並区", "Taito|台東区|Taitō", "Sumida|墨田区",
      "Koto|江東区|Kōtō", "Ota-ku|大田区|Ōta-ku", "Shiodome|汐留", "Toranomon|虎ノ門", "Akasaka|赤坂",
      "Nihonbashi|日本橋", "Kanda|神田", "Gotanda|五反田", "Osaki|大崎", "Tamachi|田町", "Hamamatsucho|浜松町",
      "Shimbashi|Shinbashi|新橋", "Yurakucho|有楽町", "Ginza|銀座", "Kyobashi|京橋", "Harajuku|原宿", "Omotesando|表参道",
      "Aoyama|青山", "Daikanyama|代官山", "Nakameguro|中目黒", "Shirokane|白金", "Azabu|麻布", "Hiroo|広尾",
      "Kichijoji|吉祥寺", "Futako-Tamagawa|Futakotamagawa|二子玉川", "Odaiba|お台場", "Toyosu|豊洲", "Kachidoki|勝どき",
      "Tsukiji|築地", "Umeda|梅田", "Namba|難波|なんば", "Shinsaibashi|心斎橋", "Yodoyabashi|淀屋橋", "Honmachi Osaka",
      "Tennoji|天王寺", "Shin-Osaka|Shin Osaka|新大阪", "Sannomiya|三宮", "Sakae", "Meieki|名駅", "Hakata|博多",
      "Tenjin|天神", "Minato Mirai|みなとみらい", "Musashi-Kosugi|Musashikosugi|武蔵小杉", "Shin-Yokohama|新横浜",
      "Kawasaki City|川崎市", "Omiya|大宮", "Urawa|浦和", "Makuhari|幕張", "Kaihin Makuhari|海浜幕張",
    ],
    metros: [
      "Greater Tokyo|Greater Tokyo Area|Tokyo Metropolitan Area|Tokyo Area|首都圏|東京圏", "Kanto|関東|Kantō",
      "Kansai|関西|Kansai Region|関西圏", "Kinki|近畿", "Keihanshin|京阪神", "Chubu|中部|Chūbu", "Tokai|Tōkai",
      "Hokuriku|北陸", "Tohoku|Tōhoku", "Kyushu|Kyūshū", "Shikoku", "Chugoku Region|Chūgoku Region|中国地方",
      "Chukyo|中京|Chūkyō", "Greater Osaka|Osaka Area", "Greater Nagoya|Nagoya Area", "Greater Fukuoka",
      "Keihin|京浜", "Shonan|湘南|Shōnan", "Tama Area|多摩", "Tokyo 23 Wards|東京23区|23区", "Yokohama Area",
    ],
  },
};

/**
 * Names the seven-market lists alone cannot classify. Keys are the canonical
 * display form; matching normalises them like every other form. A key that is
 * absent from every list becomes an ambiguous-only entry (Jersey).
 *
 * London rule: "London" defaults to GB at medium confidence ONLY when nothing
 * in the whole label evidences Canada — no Ontario, ON, Canada, or Canadian
 * city/region token anywhere. "London, Ontario", "London, ON" and
 * "London, Canada" resolve to CA at high confidence; "London; Toronto, ON" leaves
 * London ambiguous rather than guessing.
 */
export const gazetteerModifiers: Record<string, GazetteerModifier> = {
  // Required ambiguity list (spec) — candidates outside the lists are named.
  Cambridge: { ambiguous: true, note: "GB, US (MA), CA (ON)" },
  Victoria: { ambiguous: true, alsoCountries: ["SC", "HK"], note: "AU state, BC capital, Seychelles, Hong Kong" },
  Georgia: { ambiguous: true, alsoCountries: ["GE"], note: "US state or the country" },
  Richmond: { ambiguous: true, note: "US (VA/CA), CA (BC), GB (upon Thames), AU (VIC)" },
  Perth: { ambiguous: true, note: "AU, GB (Scotland), CA (ON)" },
  Newcastle: { ambiguous: true, note: "AU (NSW) or GB (upon Tyne)" },
  Hamilton: { ambiguous: true, alsoCountries: ["NZ", "BM"], note: "CA (ON), GB (Scotland), NZ, Bermuda" },
  London: { ambiguous: true, defaultCountry: "GB", note: "GB unless a Canada-side token is present" },
  Birmingham: { ambiguous: true, note: "GB or US (AL)" },
  Portland: { ambiguous: true, alsoCountries: ["AU", "GB"], note: "US (OR/ME), AU (VIC), GB (Dorset)" },
  Springfield: { ambiguous: true, alsoCountries: ["CA"], note: "many US states, AU (QLD), fictional" },
  Kingston: { ambiguous: true, alsoCountries: ["JM"], note: "CA (ON), GB (upon Thames), AU, Jamaica" },
  Halifax: { ambiguous: true, note: "CA (NS) or GB (West Yorkshire)" },
  Windsor: { ambiguous: true, alsoCountries: ["GB"], note: "CA (ON), GB (Berkshire), US" },
  Waterloo: { ambiguous: true, alsoCountries: ["BE"], note: "CA (ON), US (IA), BE" },
  Sydney: { ambiguous: true, note: "AU (NSW) or CA (NS)" },
  Salem: { ambiguous: true, note: "US (OR/MA) or IN (TN)" },
  Manchester: { ambiguous: true, note: "GB or US (NH)" },
  Vancouver: { ambiguous: true, note: "CA (BC) or US (WA)" },
  Jersey: { ambiguous: true, alsoCountries: ["JE", "US"], note: "Channel Island or New Jersey shorthand" },
  Washington: { ambiguous: true, alsoCountries: ["GB"], note: "US state or DC, GB (Tyne and Wear); 'Washington DC' and 'Washington State' are unambiguous" },
  Ontario: { ambiguous: true, note: "CA province or US (CA) city; 'Ontario, CA' stays ambiguous" },
  Paris: { ambiguous: true, alsoCountries: ["FR"], note: "FR, US (TX), CA (ON)" },
  Melbourne: { ambiguous: true, note: "AU (VIC) or US (FL)" },
  Hyderabad: { ambiguous: true, alsoCountries: ["PK"], note: "IN (Telangana) or PK (Sindh)" },
  Brighton: { ambiguous: true, note: "GB, US (CO/MA), AU (VIC)" },
  Lincoln: { ambiguous: true, note: "US (NE) or GB" },
  Durham: { ambiguous: true, note: "US (NC), GB, CA (ON)" },
  Boston: { ambiguous: true, note: "US (MA) or GB (Lincolnshire)" },
  Bath: { ambiguous: true, wholeSegmentOnly: true, alsoCountries: ["US"], note: "GB, US (ME/NY); also a word" },
  Reading: { ambiguous: true, wholeSegmentOnly: true, note: "GB (Berkshire) or US (PA); also a word" },
  // Additional collisions with well-known places outside the seven markets.
  Punjab: { ambiguous: true, alsoCountries: ["PK"] },
  Kochi: { ambiguous: true, note: "IN (Kerala) or JP (Kōchi)" },
  Oxford: { ambiguous: true, note: "GB or US (MS/OH)" },
  Bristol: { ambiguous: true, note: "GB or US (CT/TN/VA/RI)" },
  Southampton: { ambiguous: true, note: "GB, US (NY), CA (ON)" },
  Liverpool: { ambiguous: true, note: "GB or AU (NSW)" },
  Ipswich: { ambiguous: true, note: "GB (Suffolk) or AU (QLD)" },
  Dublin: { ambiguous: true, alsoCountries: ["IE"], note: "IE or US (CA/OH)" },
  Athens: { ambiguous: true, alsoCountries: ["GR"], note: "GR or US (GA/OH)" },
  Alexandria: { ambiguous: true, alsoCountries: ["EG"], note: "US (VA) or EG" },
  Canton: { ambiguous: true, alsoCountries: ["CN"], note: "US (OH) or historic Guangzhou" },
  Chantilly: { ambiguous: true, alsoCountries: ["FR"] },
  Montpelier: { ambiguous: true, alsoCountries: ["FR"] },
  Orleans: { ambiguous: true, alsoCountries: ["FR"], note: "CA (ON) or FR; 'New Orleans' is unambiguous" },
  Dieppe: { ambiguous: true, alsoCountries: ["FR"] },
  Banff: { ambiguous: true, alsoCountries: ["GB"] },
  Nelson: { ambiguous: true, alsoCountries: ["NZ", "GB"] },
  Hastings: { ambiguous: true, alsoCountries: ["NZ", "US"] },
  Canterbury: { ambiguous: true, alsoCountries: ["NZ"] },
  Queenstown: { ambiguous: true, alsoCountries: ["NZ"] },
  Devonport: { ambiguous: true, alsoCountries: ["NZ", "GB"] },
  Heidelberg: { ambiguous: true, alsoCountries: ["DE"] },
  Coburg: { ambiguous: true, alsoCountries: ["DE"] },
  Brunswick: { ambiguous: true, alsoCountries: ["DE", "US"] },
  Rhodes: { ambiguous: true, alsoCountries: ["GR"] },
  Malaga: { ambiguous: true, alsoCountries: ["ES"] },
  Ballina: { ambiguous: true, alsoCountries: ["IE"] },
  Georgetown: { ambiguous: true, alsoCountries: ["GY", "MY"], note: "many; also Guyana and Penang" },
  Dover: { ambiguous: true, alsoCountries: ["GB"], note: "US (DE/NH), GB (Kent), SG" },
  Whitefield: { ambiguous: true, alsoCountries: ["GB"], note: "IN (Bengaluru) or GB (Greater Manchester)" },
  "National Capital Region": { ambiguous: true, alsoCountries: ["PH"], note: "CA (Ottawa), IN (Delhi), PH (Manila)" },
  NCR: { ambiguous: true, alsoCountries: ["PH"], note: "Delhi NCR, Manila NCR or the company" },
  "Capital Region": { ambiguous: true, alsoCountries: ["US"], note: "CA (Alberta) or US (Albany)" },
  "Financial District": { ambiguous: true, alsoCountries: ["US"], note: "IN (Hyderabad) or US (NYC/SF)" },
  "Central Coast": { ambiguous: true, alsoCountries: ["US"] },
  "West End": { ambiguous: true, alsoCountries: ["CA"] },
  "Notting Hill": { ambiguous: true },
  Haymarket: { ambiguous: true, alsoCountries: ["US"] },
  "Olympic Park": { ambiguous: true, alsoCountries: ["GB", "US"] },
  "Park Street": { ambiguous: true, alsoCountries: ["AU", "US"] },
  Essex: { ambiguous: true, alsoCountries: ["US", "CA"], note: "GB county or US/CA counties" },
  Somerset: { ambiguous: true, alsoCountries: ["US"], note: "GB county, US (NJ/KY), SG" },
  Suffolk: { ambiguous: true, alsoCountries: ["US"], note: "GB county or US (VA/NY)" },
  Sussex: { ambiguous: true, alsoCountries: ["US"] },
  Rutland: { ambiguous: true, alsoCountries: ["US"] },
  Winchester: { ambiguous: true, alsoCountries: ["US"] },
  Elgin: { ambiguous: true, alsoCountries: ["US"] },
  Stafford: { ambiguous: true, alsoCountries: ["US"] },
  Chesterfield: { ambiguous: true, alsoCountries: ["US"] },
  Mansfield: { ambiguous: true, alsoCountries: ["US"] },
  Kettering: { ambiguous: true, alsoCountries: ["US"] },
  Brentwood: { ambiguous: true, alsoCountries: ["US"] },
  Enfield: { ambiguous: true, alsoCountries: ["US"] },
  Sutton: { ambiguous: true, alsoCountries: ["US", "CA"] },
  Soho: { ambiguous: true, alsoCountries: ["US"] },
  Chelsea: { ambiguous: true, alsoCountries: ["US"] },
  Kensington: { ambiguous: true, alsoCountries: ["US", "AU", "CA"] },
  Paddington: { ambiguous: true, alsoCountries: ["AU"] },
  "Kings Cross": { ambiguous: true, alsoCountries: ["AU"] },
  Monmouth: { ambiguous: true, alsoCountries: ["US"] },
  Midland: { ambiguous: true, alsoCountries: ["US", "CA"] },
  Logan: { ambiguous: true, alsoCountries: ["US"] },
  Rockingham: { ambiguous: true, alsoCountries: ["US"] },
  Armadale: { ambiguous: true, alsoCountries: ["GB"] },
  Claremont: { ambiguous: true, alsoCountries: ["US"] },
  Norwood: { ambiguous: true, alsoCountries: ["US"] },
  Marion: { ambiguous: true, alsoCountries: ["US"] },
  "Bedford Park": { ambiguous: true, alsoCountries: ["US"] },
  "Victoria Park": { ambiguous: true, alsoCountries: ["GB", "CA"] },
  "Spring Hill": { ambiguous: true, alsoCountries: ["US"] },
  Clayton: { ambiguous: true, alsoCountries: ["US"] },
  Newtown: { ambiguous: true, alsoCountries: ["US", "GB"] },
  Sunbury: { ambiguous: true, alsoCountries: ["US", "GB"] },
  Melton: { ambiguous: true, alsoCountries: ["GB"] },
  Williamstown: { ambiguous: true, alsoCountries: ["US"] },
  Maitland: { ambiguous: true, alsoCountries: ["US"] },
  Grafton: { ambiguous: true, alsoCountries: ["US"] },
  "Bella Vista": { ambiguous: true, alsoCountries: ["US"] },
  Redlands: { ambiguous: true, alsoCountries: ["US"] },
  Amherst: { ambiguous: true, alsoCountries: ["US"] },
  Vernon: { ambiguous: true, alsoCountries: ["US"] },
  Sidney: { ambiguous: true, alsoCountries: ["US"] },
  Bridgewater: { ambiguous: true, alsoCountries: ["US"] },
  Riverview: { ambiguous: true, alsoCountries: ["US"] },
  Jasper: { ambiguous: true, wholeSegmentOnly: true, alsoCountries: ["US"] },
  Mission: { ambiguous: true, wholeSegmentOnly: true, alsoCountries: ["US"] },
  "San Juan": { ambiguous: true, alsoCountries: ["AR", "PH"] },
  Malvern: { ambiguous: true, note: "US (PA), AU (VIC), GB (Worcestershire)" },
  Terai: { ambiguous: true, alsoCountries: ["NP"] },
  // Ordinary words: only a complete segment can be a place.
  Sterling: { wholeSegmentOnly: true }, Mobile: { wholeSegmentOnly: true }, Bend: { wholeSegmentOnly: true },
  Norman: { wholeSegmentOnly: true }, Frederick: { wholeSegmentOnly: true }, Newton: { wholeSegmentOnly: true, ambiguous: true },
  Jackson: { wholeSegmentOnly: true }, Lawrence: { wholeSegmentOnly: true }, Wayne: { wholeSegmentOnly: true },
  Troy: { wholeSegmentOnly: true }, Davis: { wholeSegmentOnly: true }, Campbell: { wholeSegmentOnly: true },
  Edison: { wholeSegmentOnly: true }, Franklin: { wholeSegmentOnly: true }, Independence: { wholeSegmentOnly: true },
  Sale: { wholeSegmentOnly: true, ambiguous: true }, Bury: { wholeSegmentOnly: true }, Derby: { wholeSegmentOnly: true, ambiguous: true, alsoCountries: ["US"] },
  Tyrone: { wholeSegmentOnly: true }, Elizabeth: { wholeSegmentOnly: true }, Mitchell: { wholeSegmentOnly: true },
  Bruce: { wholeSegmentOnly: true }, Hume: { wholeSegmentOnly: true }, Barton: { wholeSegmentOnly: true },
  Prospect: { wholeSegmentOnly: true }, Newman: { wholeSegmentOnly: true }, Katherine: { wholeSegmentOnly: true },
  Clarence: { wholeSegmentOnly: true }, Griffith: { wholeSegmentOnly: true }, Forster: { wholeSegmentOnly: true },
  Singleton: { wholeSegmentOnly: true }, Sutherland: { wholeSegmentOnly: true }, Miranda: { wholeSegmentOnly: true },
  Botany: { wholeSegmentOnly: true }, Manly: { wholeSegmentOnly: true }, Glebe: { wholeSegmentOnly: true },
  Carlton: { wholeSegmentOnly: true }, Knox: { wholeSegmentOnly: true }, Sunshine: { wholeSegmentOnly: true },
  Hunter: { wholeSegmentOnly: true }, "Tom Price": { wholeSegmentOnly: true }, Trail: { wholeSegmentOnly: true },
  Duncan: { wholeSegmentOnly: true }, Terrace: { wholeSegmentOnly: true }, Brooks: { wholeSegmentOnly: true },
  Thompson: { wholeSegmentOnly: true }, Lindsay: { wholeSegmentOnly: true }, Cochrane: { wholeSegmentOnly: true },
  Anand: { wholeSegmentOnly: true }, Erode: { wholeSegmentOnly: true }, Hassan: { wholeSegmentOnly: true },
  Puri: { wholeSegmentOnly: true }, Satellite: { wholeSegmentOnly: true }, Toyota: { wholeSegmentOnly: true },
  Hitachi: { wholeSegmentOnly: true }, Saga: { wholeSegmentOnly: true }, Mie: { wholeSegmentOnly: true },
  Tsu: { wholeSegmentOnly: true }, Kanda: { wholeSegmentOnly: true }, Sakae: { wholeSegmentOnly: true },
  Chuo: { wholeSegmentOnly: true }, Minato: { wholeSegmentOnly: true }, Koto: { wholeSegmentOnly: true },
  Kure: { wholeSegmentOnly: true }, Ubi: { wholeSegmentOnly: true }, Redhill: { wholeSegmentOnly: true },
  Bayfront: { wholeSegmentOnly: true }, Simei: { wholeSegmentOnly: true }, Eunos: { wholeSegmentOnly: true },
  Delta: { wholeSegmentOnly: true }, Ajax: { wholeSegmentOnly: true }, Hull: { wholeSegmentOnly: true, ambiguous: true },
  Concord: { wholeSegmentOnly: true }, Columbia: { wholeSegmentOnly: true }, Charleston: { wholeSegmentOnly: true },
  Hollywood: { wholeSegmentOnly: true }, Queens: { wholeSegmentOnly: true }, Bronx: { wholeSegmentOnly: true },
  Midwest: { wholeSegmentOnly: true }, Prairies: { wholeSegmentOnly: true }, Maritimes: { wholeSegmentOnly: true },
  Midlands: { wholeSegmentOnly: true }, Stoke: { wholeSegmentOnly: true }, Burton: { wholeSegmentOnly: true },
  Ely: { wholeSegmentOnly: true }, Ayr: { wholeSegmentOnly: true }, Hove: { wholeSegmentOnly: true },
  Wagga: { wholeSegmentOnly: true }, Eugene: { wholeSegmentOnly: true }, Flint: { wholeSegmentOnly: true },
  Providence: { wholeSegmentOnly: true }, Richardson: { wholeSegmentOnly: true }, Katy: { wholeSegmentOnly: true },
  Casper: { wholeSegmentOnly: true }, Savannah: { wholeSegmentOnly: true },
  Toledo: { ambiguous: true, alsoCountries: ["ES"] }, Olympia: { ambiguous: true, alsoCountries: ["GR"] },
  "Santa Cruz": { ambiguous: true, alsoCountries: ["BO", "ES"] }, "New Brunswick": { ambiguous: true, note: "CA province or US (NJ) city" },
};

/**
 * Region codes that are also ordinary words or abbreviations. Accepted only
 * directly after a known city of the same country ("Austin, TX" style — the
 * city segment must precede the code), beside an explicit country
 * ("US-TX", "TX, USA") — never on their own.
 */
export const guardedRegionCodes: readonly string[] = [
  "DE", "ME", "OR", "IT", "HI", "OK", "NO", "ID", "IL", "AS", "BE", "IN", "ON", "CO", "NE", "OH", "MD", "MB", "NB",
  "PE", "YT", "SA", "ACT", "MS", "MT", "MA", "AL",
];

/** Every code of these countries is guarded (most Indian state codes collide with ISO country codes: HR, BR, GA, CH, PY, TN …). */
export const anchorRequiredCodeCountries: readonly SupportedMarket[] = ["IN"];

/**
 * Codes that read both as a US state and as a country label. They never
 * resolve alone: "Ontario, CA" and "Remote - IN" stay ambiguous. With a
 * known city in front they follow the city ("San Francisco, CA" → US,
 * "Toronto, CA" → CA, "Indianapolis, IN" → US, "Bengaluru, IN" → IN).
 */
export const countryCollisionCodes: Record<string, { region: SupportedMarket; country: SupportedMarket }> = {
  CA: { region: "US", country: "CA" },
  IN: { region: "US", country: "IN" },
};

/** Codes that are ambiguous inside the seven markets even when written in upper case. */
export const ambiguousRegionCodeNotes: Record<string, string> = {
  WA: "Washington (US) or Western Australia",
  NT: "Northwest Territories (CA) or Northern Territory (AU)",
  SA: "South Australia; also South Africa / Saudi Arabia",
  TN: "Tennessee (US) or Tamil Nadu (IN)",
  MP: "Madhya Pradesh (IN); Northern Mariana Islands is not a launch market",
};
